- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - ../group_vars/all/vault.yml
  collections:
    - scaleway.cloud

  vars:
    servers:
      - name: "{{ server_name_1 }}"
        region: "{{ server_zone_1 }}"
        image: "{{ image_1 }}"
        commercial_type: "{{ commercial_type }}"
      - name: "{{ server_name_2 }}"
        region: "{{ server_zone_2 }}"
        image: "{{ image_2 }}"
        commercial_type: "{{ commercial_type }}"

  tasks:
    - name: Créer ou démarrer les instances Scaleway
      community.general.scaleway_compute:
        state: running
        api_token: "{{ scw_secret_key }}"
        name: "{{ item.name }}"
        project: "{{ scw_default_project_id }}"
        region: "{{ item.region }}"
        image: "{{ item.image }}"
        commercial_type: "{{ item.commercial_type }}"
      loop: "{{ servers }}"
      register: server_infos

    - name: Afficher les détails des serveurs créés
      debug:
        var: server_infos.results

    - name: Attendre que SSH soit disponible sur chaque serveur
      wait_for:
        host: "{{ item.instance.public_ip }}"
        port: 22
        timeout: 300
        delay: 30
      loop: "{{ server_infos.results }}"
      when: item.instance.public_ip is defined

    - name: Afficher les adresses IP publiques des serveurs
      debug:
        msg: "Serveur {{ item.item.name }} a l'IP publique {{ item.instance.public_ip }}"
      loop: "{{ server_infos.results }}"
      when: item.instance.public_ip is defined
