---
- hosts: localhost
  gather_facts: no
  vars_files:
    - ../group_vars/all/vault.yml
  collections:
    - scaleway.cloud

  tasks:
    # - name: Authenticate with Scaleway
    #   scaleway_login:
    #     access_key: "{{ scw_access_key }}"
    #     secret_key: "{{ scw_secret_key }}"

    - name: Create or Start Scaleway Instance
      community.general.scaleway_compute:
        state: running
        api_token: "{{ scw_secret_key }}"
        name: "{{ server_name }}"
        project: "{{ scw_default_project_id }}"
        region: "{{ server_zone }}"
        image: 71fbae84-e539-43e3-b005-10d1fb69ea99
        commercial_type: STARDUST1-S
      register: server_info

    - name: Display Server Details
      debug:
        var: server_info

    - name: Wait for SSH to be available
      wait_for:
        host: "{{ server_info.instance.public_ip }}"
        port: 22
        timeout: 300
        delay: 30
      when: server_info.instance.public_ip is defined
