---
- hosts: localhost
  vars_files:
    - ../group_vars/all/vault.yml
  tasks:
  - name: Stop server instance
    community.general.scaleway_compute:
      state: stopped
      api_token: "{{ scw_secret_key }}"
      name: "{{ server_name }}"
      project: "{{ scw_default_project_id }}"
      region: "{{ server_zone }}"
      image: 71fbae84-e539-43e3-b005-10d1fb69ea99
      commercial_type: STARDUST1-S
    register: server_info

  - name: Display Server Details
    debug:
       var: server_info