---
- hosts: localhost
  gather_facts: false
  vars_files:
    - ../group_vars/all/vault.yml
  collections:
    - scaleway.cloud

  vars:
    servers:
      - name: "{{ server_name_1 }}"
        region: "{{ server_zone_1 }}"
        image: "{{ image_1 }}"
        commercial_type: "{{ commercial_type }}"
      - name: "{{ server_name_2 }}"
        region: "{{ server_zone_2 }}"
        image: "{{ image_2 }}"
        commercial_type: "{{ commercial_type }}"

  tasks:
    - name: Stop servers
      community.general.scaleway_compute:
        state: stopped
        api_token: "{{ scw_secret_key }}"
        name: "{{ item.name }}"
        project: "{{ scw_default_project_id }}"
        region: "{{ item.region }}"
        image: "{{ item.image }}"
        commercial_type: "{{ item.commercial_type }}"
      loop: "{{ servers }}"
      register: server_infos

    - name: Display Server Details
      debug:
        var: server_infos.results
